[package]
name = "vortexkey"
version = "1.0.1"
edition = "2024"

[dependencies]
anyhow = "1.0.97"
chrono = "0.4.40"
clap = { version = "4.5.35", features = ["derive"] }
glob = "0.3.2"
image = "0.25.6"
sha2 = "0.10.8"
